name: Deploy to AWS EC2

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up SSH & Deploy
        run: |
          echo "${{ secrets.EC2_SSH_PRIVATE_KEY }}" > private_key.pem
          chmod 600 private_key.pem

          ssh -o StrictHostKeyChecking=no -i private_key.pem ubuntu@${{ secrets.AWS_HOST }} << 'EOF'
            # Ensure project directory exists
            if [ ! -d "/home/ubuntu/Student-Attendance-System" ]; then
              git clone https://github.com/dhanarajrk/Student-Attendance-System.git /home/ubuntu/Student-Attendance-System
            fi
            cd /home/ubuntu/Student-Attendance-System
            git pull origin main
            docker-compose down
            docker-compose up -d --build
          EOF

          rm -f private_key.pem
